/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

/**
 *
 * @author NádasViktóriaMária(S
 */
public class _LightOnGUInezet extends javax.swing.JFrame {

    /**
     * Creates new form _LightOnGUInezet
     */
    public _LightOnGUInezet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelJatekTer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelLepesSzamlalo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanelCimKeret = new javax.swing.JPanel();
        jTextFieldCim = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBetolt = new javax.swing.JMenu();
        jMenuItemMentes = new javax.swing.JMenuItem();
        jMenuItemBetolt = new javax.swing.JMenuItem();
        jMenuItem1ujJatek = new javax.swing.JMenuItem();
        jMenuItemKilepes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelJatekTer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 12, 12, 12, new java.awt.Color(102, 0, 0)));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(60, 60));

        jButton2.setBackground(new java.awt.Color(102, 0, 51));
        jButton2.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelLepesSzamlalo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabelLepesSzamlalo.setForeground(new java.awt.Color(0, 102, 0));
        jLabelLepesSzamlalo.setText("Lépés számláló:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setEnabled(false);

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setPreferredSize(new java.awt.Dimension(60, 60));

        jButton4.setBackground(new java.awt.Color(51, 204, 0));
        jButton4.setPreferredSize(new java.awt.Dimension(60, 60));

        jButton5.setBackground(new java.awt.Color(51, 204, 0));
        jButton5.setPreferredSize(new java.awt.Dimension(60, 60));

        jButton6.setBackground(new java.awt.Color(102, 0, 51));
        jButton6.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 0, 51));
        jButton8.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 0, 51));
        jButton9.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 0, 51));
        jButton10.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelJatekTerLayout = new javax.swing.GroupLayout(jPanelJatekTer);
        jPanelJatekTer.setLayout(jPanelJatekTerLayout);
        jPanelJatekTerLayout.setHorizontalGroup(
            jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJatekTerLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLepesSzamlalo)
                    .addGroup(jPanelJatekTerLayout.createSequentialGroup()
                        .addGroup(jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJatekTerLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelJatekTerLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelJatekTerLayout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanelJatekTerLayout.setVerticalGroup(
            jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJatekTerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanelJatekTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLepesSzamlalo)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanelCimKeret.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(102, 0, 51)));

        jTextFieldCim.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldCim.setFont(new java.awt.Font("Snap ITC", 0, 48)); // NOI18N
        jTextFieldCim.setForeground(new java.awt.Color(0, 102, 0));
        jTextFieldCim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCim.setText("Light On!");
        jTextFieldCim.setBorder(null);
        jTextFieldCim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCimKeretLayout = new javax.swing.GroupLayout(jPanelCimKeret);
        jPanelCimKeret.setLayout(jPanelCimKeretLayout);
        jPanelCimKeretLayout.setHorizontalGroup(
            jPanelCimKeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCimKeretLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jTextFieldCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanelCimKeretLayout.setVerticalGroup(
            jPanelCimKeretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCimKeretLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextFieldCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(242, 242, 242));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 0, 12, new java.awt.Color(102, 0, 51)));

        jMenuBetolt.setForeground(new java.awt.Color(102, 0, 0));
        jMenuBetolt.setText("Menü");
        jMenuBetolt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jMenuItemMentes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jMenuItemMentes.setForeground(new java.awt.Color(0, 102, 0));
        jMenuItemMentes.setText("Mentés");
        jMenuBetolt.add(jMenuItemMentes);

        jMenuItemBetolt.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jMenuItemBetolt.setForeground(new java.awt.Color(0, 102, 0));
        jMenuItemBetolt.setText("Betöltés");
        jMenuBetolt.add(jMenuItemBetolt);

        jMenuItem1ujJatek.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jMenuItem1ujJatek.setForeground(new java.awt.Color(204, 102, 0));
        jMenuItem1ujJatek.setText("Új játék");
        jMenuBetolt.add(jMenuItem1ujJatek);

        jMenuItemKilepes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jMenuItemKilepes.setForeground(new java.awt.Color(102, 0, 0));
        jMenuItemKilepes.setText("Kilépés");
        jMenuBetolt.add(jMenuItemKilepes);

        jMenuBar1.add(jMenuBetolt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCimKeret, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelJatekTer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelCimKeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelJatekTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldCimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCimActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_LightOnGUInezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_LightOnGUInezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_LightOnGUInezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_LightOnGUInezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _LightOnGUInezet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabelLepesSzamlalo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBetolt;
    private javax.swing.JMenuItem jMenuItem1ujJatek;
    private javax.swing.JMenuItem jMenuItemBetolt;
    private javax.swing.JMenuItem jMenuItemKilepes;
    private javax.swing.JMenuItem jMenuItemMentes;
    private javax.swing.JPanel jPanelCimKeret;
    private javax.swing.JPanel jPanelJatekTer;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCim;
    // End of variables declaration//GEN-END:variables
}
